### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by antonioLuis23** [benjohnson/atom-django-templates#19] opened 2015-05-03 16:17 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\Antonio\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:566:9)
<unknown> (C:\Users\Antonio\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:168:43)
Package.measure (C:\Users\Antonio\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
Package.load (C:\Users\Antonio\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:161:12)
```

**Comment by chrisdl** [comment] 2015-05-13 14:49
duplicate of #17

**Closed** 2015-05-23 13:26 UTC
